/* msg\unsupdos.c: THIS FILE IS AUTO-GENERATED BY GENMSG.C -- DO NOT MODIFY! */
_asm {
  push ds
  push dx
  push ax
  call getip
  S000 db 87,114,111,110,103,32,68,79,83,32,118,101,114,115,105,111
  S001 db 110,33,32,84,104,105,115,32,118,101,114,115,105,111,110,32
  S002 db 111,102,32,69,116,104,101,114,68,70,83,32,114,101,113,117
  S003 db 105,114,101,115,32,77,83,45,68,79,83,32,51,46,50,48
  S004 db 32,45,32,51,46,51,48,46,13,10,'$'
 getip:
  pop dx
  push cs
  pop ds
  mov ah,9h
  int 21h
  pop ax
  pop dx
  pop ds
};
